// Player Set Actions
export const SET_TOTAL_FUND_RAISED = "SET_TOTAL_FUND_RAISED";
export const SET_TOTAL_APPLICATION = "SET_TOTAL_APPLICATION";
export const SET_APPLICATION_LIST = "SET_APPLICATION_LIST";
export const SET_CONTRACT_INSTANCE = "SET_CONTRACT_INSTANCE";
